### ISSUE TITLE
ConsoleShell not doing anything

### ISSUE THREAD

**Issue by iceblu3710** [thijse/Arduino-CmdMessenger#10]
On my Pro Mini 5V 16MHz I have used the "Communications - SerialEvent" example to prove I can send and receive to the board. I load up the ConsoleShell example and it displays the console options but ignores all input.

In fact none of the examples react to serial monitor input.

Does the library work with the Pro Mini?

**Comment by thijse** [comment]
It should! Have you tried setting DTREnable to true and false? That may do
the trick.
