### ISSUE TITLE
I just need to send strings between my arduino and the pi

### ISSUE THREAD

**Issue by iHover01** [thijse/Arduino-CmdMessenger#19]
anyone have a simple example of how to send a string to the ardino and send a string to the pi? 
If I can send a string back and forth than I can do anything need in my code. 
if I can get the pi to send the arduino "Hi im the PI" and the ardino to send "Nice to meet you" I can do anything else I need.  disregard after going through send/receive example a couple tims  figured it out

**Comment by thijse** [comment]
Hi, 

Have a look at the [Python implementation](https://github.com/harmsm/PyCmdMessenger) , and in particular [the example](https://github.com/harmsm/PyCmdMessenger/blob/master/examples/python-basic.py). Good luck!

**Comment by iHover01** [comment]
Got it thanks
