### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by BytesGuy** [thijse/Arduino-CmdMessenger#5]
Hey Thijs, thanks for the great library! I was trying to implement virtually the same thing myself, but it was taking too long and had some nasty bugs. Stumbling upon this has got me up and running once again with minimal effort.

I have created some nuget packages for CmdMessenger to make it easier to install and use in Visual Studio projects - just wanted to know if you are happy for me to publish and maintain them on nuget.org

I have split the bluetooth transport layer into it's own package as it has a dependency (just keeps the core package nice and lean).

**Comment by hunyadizsolt** [comment]
Yes very interested. Pleaseeeee. Thank you

**Comment by thijse** [comment]
Awesome! Having Nuget packages would be great, and I am not at all opposed to somebody else doing all the work in maintaining them :-). I will contact you to discuss this.

**Comment by Rast1234** [comment]
Excuse me, i can't find the CmdMessenger package on NuGet. Can you post a link?
